### ISSUE TITLE
Links to OST

### ISSUE THREAD

**Issue by gaborvar** [MicrosoftDocs/microsoft-365-docs#7018]
[Enter feedback here]
This page is a key reference point for key discussions on Cloud security and compliance. Thx!

Links in the article to various licensing and compliance documents of Microsoft are broken. E.g. Online Services Terms docu has moved to Product Terms site. Can you update the links accordingly? E.g. https://go.microsoft.com/fwlink/p/?linkid=862403 or https://go.microsoft.com/fwlink/p/?linkid=864390
Note that the definition of categories of data were update on Sept 15 in the new DPA aka.ms/dpa. In case you refer to external pages for categories of data, pls use updated pages.

Thank you, and thanks for updating the page for Viva!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c6fa7b-7e9e-21a5-40da-adbd35040ec1
* Version Independent ID: 530df3b2-2048-8351-2f09-59e604aedf5b
* Content: [Microsoft 365 data locations - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/o365-data-locations?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/o365-data-locations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/o365-data-locations.md)
* Service: **o365-solutions**
* GitHub Login: @dmwmsft
* Microsoft Alias: **deanw**

**Comment by msbemba** [comment]
@gaborvar Thank you for your feedback. The Links that you reported to be problematic are fixed in the backend and I'm able to access this now.

If this is just a locale issue, You can access the  Online Services Privacy and Security Terms, here https://www.microsoft.com/licensing/terms/product/PrivacyandSecurityTerms/all

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @gaborvar Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by gaborvar** [comment]
Thank you for the update. 
@msbemba in your comment you are referring to the valid and OST link: https://www.microsoft.com/licensing/terms/product/PrivacyandSecurityTerms/all
However in the article I still see a redirected link https://go.microsoft.com/fwlink/p/?linkid=864390 that points to https://www.microsoft.com/licensing/docs in two places. This is incorrect. You also see an error message saying that the link should be updated. That error message should not appear and should not require the user to look for the new OST link manually after landing on the generic licensing page.

**Comment by yogkumgit** [comment]
@msbemba please review.

**Comment by msbemba** [comment]
@gaborvar Thank you for your feedback. I see the correct link in the article as well

![image](https://user-images.githubusercontent.com/45987684/145033834-5747786d-7001-4c5c-b9c3-2ce84edadc4f.png)


Could you please point me to the links which are redirecting or incorrect? 

Thanks
Sri

**Comment by gaborvar** [comment]
The link in your screenshot is correct. It points to the page that replaced the OST.
However, under the first item in the FAQ there are two other occurrences of links that used to point to the OST which are now broken:
"In the Microsoft Online Services Terms, Microsoft makes contractual commitments regarding customer data/your data. We refer to core customer data as the customer data that is committed to be stored at rest only within your region according to the Microsoft Online Services Terms."
They should also point to the same page i.e. https://www.microsoft.com/licensing/terms/product/PrivacyandSecurityTerms/all
. OST does not exist any more. For full clarity you may want to mention that earlier versions of OST (which is still in force for some of the customers) are still available. Details are described at https://www.microsoft.com/en-gb/licensing/product-licensing/products

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@gaborvar Thank you for the response. I have fixed those two links as well via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7128

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gaborvar Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
